---
- name: Add required dependencies.
  apt:
    name:
      - apt-transport-https
      - gnupg2
    state: present

- name: Add Elasticsearch apt key (url).
  apt_key:
    url: "{{ elasticsearch_apt_key_url | d(omit) }}"
    state: present
  when: elasticsearch_apt_key_url | d('') | length > 0

- name: Add Elasticsearch apt key (data).
  apt_key:
    data: "{{ elasticsearch_apt_key_data | d(omit) }}"
    state: present
  when: elasticsearch_apt_key_data | d('') | length > 0

- name: Add Elasticsearch repository.
  apt_repository:
    repo: "{{ elasticsearch_apt_repo_url }}"
    state: present
    update_cache: true
